name: NRD sample
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install windows-sdk-10.0 cmake -y

      - name: Deploy
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\1-Deploy.bat

      - name: Build
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\2-Build.bat

  Build-Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Deploy
        run: bash 1-Deploy.sh

      - name: Build
        run: bash 2-Build.sh
