name: NRD sample
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install windows-sdk-10.0 cmake -y

      - name: Install Vulkan
        run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
           echo "Downloading Vulkan SDK from https://sdk.lunarg.com/sdk/download/$ver/windows/vulkansdk-windows-X64-$ver.exe"
          $ProgressPreference = 'SilentlyContinue'
           Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/vulkansdk-windows-X64-$ver.exe" -OutFile VulkanSDK.exe
          .\VulkanSDK.exe --root C:\VulkanSDK --accept-licenses --default-answer --confirm-command install

      - name: Deploy
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\1-Deploy.bat

      - name: Build
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\2-Build.bat

      - name: Upload NRD Sample as artefact
        uses: actions/upload-artifact@v4
        with:
          name: NRD Sample
          path: |
            README.md
            3-Run NRD sample.bat
            _Bin/Release/
            _Data/
            _Shaders/