name: NRD sample
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install windows-sdk-10.0 cmake -y

      - name: Deploy
        run: .\1-Deploy.bat

      - name: Build
        run: .\2-Build.bat

  Build-Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Vulkan
        run: |
          sudo apt install -y wget
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
          sudo apt install -y vulkan-sdk

      - name: Deploy
        run: bash 1-Deploy.sh

      - name: Build
        run: bash 2-Build.sh
